2025-04-11 11:13:15,362 INFO    MainThread:1624650 [wandb_setup.py:_flush():76] Current SDK version is 0.17.1
2025-04-11 11:13:15,363 INFO    MainThread:1624650 [wandb_setup.py:_flush():76] Configure stats pid to 1624650
2025-04-11 11:13:15,363 INFO    MainThread:1624650 [wandb_setup.py:_flush():76] Loading settings from /home/hawk/.config/wandb/settings
2025-04-11 11:13:15,363 INFO    MainThread:1624650 [wandb_setup.py:_flush():76] Loading settings from /home/hawk/Desktop/Heavy Detector/Heavy-Clutter-Detection/finalDiffusion/wandb/settings
2025-04-11 11:13:15,363 INFO    MainThread:1624650 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2025-04-11 11:13:15,363 INFO    MainThread:1624650 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2025-04-11 11:13:15,363 INFO    MainThread:1624650 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2025-04-11 11:13:15,363 INFO    MainThread:1624650 [wandb_setup.py:_flush():76] Applying login settings: {}
2025-04-11 11:13:15,363 INFO    MainThread:1624650 [wandb_init.py:_log_setup():520] Logging user logs to /home/hawk/Desktop/Heavy Detector/Heavy-Clutter-Detection/finalDiffusion/wandb/run-20250411_111315-rhqmhib0/logs/debug.log
2025-04-11 11:13:15,364 INFO    MainThread:1624650 [wandb_init.py:_log_setup():521] Logging internal logs to /home/hawk/Desktop/Heavy Detector/Heavy-Clutter-Detection/finalDiffusion/wandb/run-20250411_111315-rhqmhib0/logs/debug-internal.log
2025-04-11 11:13:15,364 INFO    MainThread:1624650 [wandb_init.py:_jupyter_setup():466] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7706ecb18f70>
2025-04-11 11:13:15,364 INFO    MainThread:1624650 [wandb_init.py:init():560] calling init triggers
2025-04-11 11:13:15,364 INFO    MainThread:1624650 [wandb_init.py:init():567] wandb.init called with sweep_config: {}
config: {'SNR': 10, 'CNR': 15, 'beta_end': 0.02, 'beta_start': 0.0001, 'batch_size': 16, 'num_epochs': 400, 'noise_steps': 2000, 'num_workers': 4, 'dataset_size': 500, 'time_emb_dim': 256, 'learning_rate': 0.0001, 'scheduler_type': 'linear'}
2025-04-11 11:13:15,364 INFO    MainThread:1624650 [wandb_init.py:init():610] starting backend
2025-04-11 11:13:15,364 INFO    MainThread:1624650 [wandb_init.py:init():614] setting up manager
2025-04-11 11:13:15,367 INFO    MainThread:1624650 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-04-11 11:13:15,368 INFO    MainThread:1624650 [wandb_init.py:init():622] backend started and connected
2025-04-11 11:13:15,375 INFO    MainThread:1624650 [wandb_run.py:_label_probe_notebook():1334] probe notebook
2025-04-11 11:13:15,375 INFO    MainThread:1624650 [wandb_run.py:_label_probe_notebook():1344] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2025-04-11 11:13:15,375 INFO    MainThread:1624650 [wandb_init.py:init():711] updated telemetry
2025-04-11 11:13:15,380 INFO    MainThread:1624650 [wandb_init.py:init():744] communicating run to backend with 90.0 second timeout
2025-04-11 11:14:45,459 ERROR   MainThread:1624650 [wandb_init.py:init():770] encountered error: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2025-04-11 11:14:45,459 ERROR   MainThread:1624650 [wandb_init.py:init():1181] error in wandb.init()
Traceback (most recent call last):
  File "/home/hawk/.local/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1171, in init
    return wi.init()
  File "/home/hawk/.local/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 776, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
